### ISSUE TITLE
Send doesnt resolve

### ISSUE THREAD

**Issue by Jamsie100** [adrianmcli/ganache-jest-example#2]
to fix:
update web3 to 1.0.0@-beta48
gas wasn't enough so had to estimateGas()

https://github.com/FeiShepherd/ganache-jest-example/commit/d75306bf6a50da414ccb071d1d8342e8c13503a0

**Comment by adrianmcli** [comment]
@FeiShepherd We've actually pinned a lot of our projects at Truffle to use `beta35` due to breaking changes happening in between Web3.js beta versions. Does 48 work for this repo? If so, a PR would be greatly appreciated.

**Comment by adrianmcli** [comment]
@FeiShepherd is this now solved? If so, can you close this issue?
